# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R2P_GUI_ui.ui'
#
# Created: Mon Sep 23 15:00:45 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(640, 500)
        self.centralWidget = QtGui.QWidget(window)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLogical = QtGui.QWidget()
        self.tabLogical.setObjectName("tabLogical")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabLogical)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushLogicalCollapse = QtGui.QPushButton(self.tabLogical)
        self.pushLogicalCollapse.setObjectName("pushLogicalCollapse")
        self.horizontalLayout_8.addWidget(self.pushLogicalCollapse)
        self.pushLogicalExpand = QtGui.QPushButton(self.tabLogical)
        self.pushLogicalExpand.setObjectName("pushLogicalExpand")
        self.horizontalLayout_8.addWidget(self.pushLogicalExpand)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushLogicalRefresh = QtGui.QPushButton(self.tabLogical)
        self.pushLogicalRefresh.setAutoDefault(True)
        self.pushLogicalRefresh.setDefault(True)
        self.pushLogicalRefresh.setObjectName("pushLogicalRefresh")
        self.horizontalLayout_8.addWidget(self.pushLogicalRefresh)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.treeLogical = QtGui.QTreeView(self.tabLogical)
        self.treeLogical.setObjectName("treeLogical")
        self.gridLayout_4.addWidget(self.treeLogical, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabLogical, "")
        self.tabPhysical = QtGui.QWidget()
        self.tabPhysical.setObjectName("tabPhysical")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabPhysical)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushPhysicalCollapse = QtGui.QPushButton(self.tabPhysical)
        self.pushPhysicalCollapse.setObjectName("pushPhysicalCollapse")
        self.horizontalLayout_6.addWidget(self.pushPhysicalCollapse)
        self.pushPhysicalExpand = QtGui.QPushButton(self.tabPhysical)
        self.pushPhysicalExpand.setObjectName("pushPhysicalExpand")
        self.horizontalLayout_6.addWidget(self.pushPhysicalExpand)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushPhysicalRefresh = QtGui.QPushButton(self.tabPhysical)
        self.pushPhysicalRefresh.setAutoDefault(True)
        self.pushPhysicalRefresh.setDefault(True)
        self.pushPhysicalRefresh.setObjectName("pushPhysicalRefresh")
        self.horizontalLayout_6.addWidget(self.pushPhysicalRefresh)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.treePhysical = QtGui.QTreeView(self.tabPhysical)
        self.treePhysical.setObjectName("treePhysical")
        self.gridLayout_3.addWidget(self.treePhysical, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabPhysical, "")
        self.tabBootloader = QtGui.QWidget()
        self.tabBootloader.setObjectName("tabBootloader")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabBootloader)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelBootTopic = QtGui.QLabel(self.tabBootloader)
        self.labelBootTopic.setObjectName("labelBootTopic")
        self.horizontalLayout_4.addWidget(self.labelBootTopic)
        self.lineBootTopic = QtGui.QLineEdit(self.tabBootloader)
        self.lineBootTopic.setPlaceholderText("BOOT_MyModule")
        self.lineBootTopic.setObjectName("lineBootTopic")
        self.horizontalLayout_4.addWidget(self.lineBootTopic)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushBootRefresh = QtGui.QPushButton(self.tabBootloader)
        self.pushBootRefresh.setAutoDefault(True)
        self.pushBootRefresh.setDefault(True)
        self.pushBootRefresh.setObjectName("pushBootRefresh")
        self.horizontalLayout_4.addWidget(self.pushBootRefresh)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.tableApps = QtGui.QTableView(self.tabBootloader)
        self.tableApps.setObjectName("tableApps")
        self.gridLayout_2.addWidget(self.tableApps, 1, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.tabBootloader)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineModulePath = QtGui.QLineEdit(self.tabBootloader)
        self.lineModulePath.setObjectName("lineModulePath")
        self.horizontalLayout_2.addWidget(self.lineModulePath)
        self.pushModulePath = QtGui.QPushButton(self.tabBootloader)
        self.pushModulePath.setObjectName("pushModulePath")
        self.horizontalLayout_2.addWidget(self.pushModulePath)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.labelAppPath = QtGui.QLabel(self.tabBootloader)
        self.labelAppPath.setObjectName("labelAppPath")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelAppPath)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineAppPath = QtGui.QLineEdit(self.tabBootloader)
        self.lineAppPath.setPlaceholderText("/opt/r2p/apps/MyApp")
        self.lineAppPath.setObjectName("lineAppPath")
        self.horizontalLayout_5.addWidget(self.lineAppPath)
        self.pushAppPath = QtGui.QPushButton(self.tabBootloader)
        self.pushAppPath.setObjectName("pushAppPath")
        self.horizontalLayout_5.addWidget(self.pushAppPath)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.labelAppName = QtGui.QLabel(self.tabBootloader)
        self.labelAppName.setObjectName("labelAppName")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelAppName)
        self.lineAppName = QtGui.QLineEdit(self.tabBootloader)
        self.lineAppName.setPlaceholderText("MyApp")
        self.lineAppName.setObjectName("lineAppName")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineAppName)
        self.labelStackSize = QtGui.QLabel(self.tabBootloader)
        self.labelStackSize.setObjectName("labelStackSize")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelStackSize)
        self.spinStackSize = QtGui.QSpinBox(self.tabBootloader)
        self.spinStackSize.setMinimum(32)
        self.spinStackSize.setMaximum(16384)
        self.spinStackSize.setProperty("value", 1024)
        self.spinStackSize.setObjectName("spinStackSize")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.spinStackSize)
        self.progressBootloader = QtGui.QProgressBar(self.tabBootloader)
        self.progressBootloader.setEnabled(False)
        self.progressBootloader.setProperty("value", 100)
        self.progressBootloader.setTextVisible(True)
        self.progressBootloader.setInvertedAppearance(False)
        self.progressBootloader.setObjectName("progressBootloader")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.progressBootloader)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushBootReboot = QtGui.QPushButton(self.tabBootloader)
        self.pushBootReboot.setObjectName("pushBootReboot")
        self.horizontalLayout_7.addWidget(self.pushBootReboot)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.pushBootRemoveAll = QtGui.QPushButton(self.tabBootloader)
        self.pushBootRemoveAll.setObjectName("pushBootRemoveAll")
        self.horizontalLayout_7.addWidget(self.pushBootRemoveAll)
        self.pushBootRemoveLast = QtGui.QPushButton(self.tabBootloader)
        self.pushBootRemoveLast.setObjectName("pushBootRemoveLast")
        self.horizontalLayout_7.addWidget(self.pushBootRemoveLast)
        self.pushInstall = QtGui.QPushButton(self.tabBootloader)
        self.pushInstall.setObjectName("pushInstall")
        self.horizontalLayout_7.addWidget(self.pushInstall)
        self.formLayout_2.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_4 = QtGui.QLabel(self.tabBootloader)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.tabBootloader)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineModuleElf = QtGui.QLineEdit(self.tabBootloader)
        self.lineModuleElf.setPlaceholderText("/opt/r2p/modules/MyModule/build/MyModule.elf")
        self.lineModuleElf.setObjectName("lineModuleElf")
        self.horizontalLayout_9.addWidget(self.lineModuleElf)
        self.pushModuleElf = QtGui.QPushButton(self.tabBootloader)
        self.pushModuleElf.setObjectName("pushModuleElf")
        self.horizontalLayout_9.addWidget(self.pushModuleElf)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineAppSrcElf = QtGui.QLineEdit(self.tabBootloader)
        self.lineAppSrcElf.setObjectName("lineAppSrcElf")
        self.horizontalLayout_10.addWidget(self.lineAppSrcElf)
        self.pushAppSrcElf = QtGui.QPushButton(self.tabBootloader)
        self.pushAppSrcElf.setObjectName("pushAppSrcElf")
        self.horizontalLayout_10.addWidget(self.pushAppSrcElf)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_2 = QtGui.QLabel(self.tabBootloader)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineAppDstElf = QtGui.QLineEdit(self.tabBootloader)
        self.lineAppDstElf.setPlaceholderText("/opt/r2p/apps/MyApp/build/MyApp_linked.elf")
        self.lineAppDstElf.setObjectName("lineAppDstElf")
        self.horizontalLayout_11.addWidget(self.lineAppDstElf)
        self.pushAppDstElf = QtGui.QPushButton(self.tabBootloader)
        self.pushAppDstElf.setObjectName("pushAppDstElf")
        self.horizontalLayout_11.addWidget(self.pushAppDstElf)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabBootloader, "")
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.formLayout = QtGui.QFormLayout(self.tabSettings)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelR2pPath = QtGui.QLabel(self.tabSettings)
        self.labelR2pPath.setObjectName("labelR2pPath")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelR2pPath)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineR2pPath = QtGui.QLineEdit(self.tabSettings)
        self.lineR2pPath.setPlaceholderText("/opt/r2p")
        self.lineR2pPath.setObjectName("lineR2pPath")
        self.horizontalLayout.addWidget(self.lineR2pPath)
        self.pushR2pPath = QtGui.QPushButton(self.tabSettings)
        self.pushR2pPath.setText("...")
        self.pushR2pPath.setObjectName("pushR2pPath")
        self.horizontalLayout.addWidget(self.pushR2pPath)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.labelChibiosPath = QtGui.QLabel(self.tabSettings)
        self.labelChibiosPath.setObjectName("labelChibiosPath")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelChibiosPath)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineChibiosPath = QtGui.QLineEdit(self.tabSettings)
        self.lineChibiosPath.setPlaceholderText("/opt/chibios")
        self.lineChibiosPath.setObjectName("lineChibiosPath")
        self.horizontalLayout_3.addWidget(self.lineChibiosPath)
        self.pushChibiosPath = QtGui.QPushButton(self.tabSettings)
        self.pushChibiosPath.setText("...")
        self.pushChibiosPath.setObjectName("pushChibiosPath")
        self.horizontalLayout_3.addWidget(self.pushChibiosPath)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.labelTransport = QtGui.QLabel(self.tabSettings)
        self.labelTransport.setObjectName("labelTransport")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTransport)
        self.comboTransport = QtGui.QComboBox(self.tabSettings)
        self.comboTransport.setEnabled(False)
        self.comboTransport.setObjectName("comboTransport")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboTransport)
        self.widgetTransportOptions = QtGui.QWidget(self.tabSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetTransportOptions.sizePolicy().hasHeightForWidth())
        self.widgetTransportOptions.setSizePolicy(sizePolicy)
        self.widgetTransportOptions.setObjectName("widgetTransportOptions")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.widgetTransportOptions)
        self.tabWidget.addTab(self.tabSettings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        window.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(window)
        self.statusBar.setObjectName("statusBar")
        window.setStatusBar(self.statusBar)

        self.retranslateUi(window)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.pushPhysicalCollapse, QtCore.SIGNAL("clicked()"), self.treePhysical.collapseAll)
        QtCore.QObject.connect(self.pushPhysicalExpand, QtCore.SIGNAL("clicked()"), self.treePhysical.expandAll)
        QtCore.QObject.connect(self.pushBootRefresh, QtCore.SIGNAL("clicked()"), window.bootRefreshApps)
        QtCore.QObject.connect(self.pushBootRemoveAll, QtCore.SIGNAL("clicked()"), window.bootRemoveAll)
        QtCore.QObject.connect(self.pushBootRemoveLast, QtCore.SIGNAL("clicked()"), window.bootRemoveLast)
        QtCore.QObject.connect(self.pushInstall, QtCore.SIGNAL("clicked()"), window.bootInstall)
        QtCore.QObject.connect(self.pushBootReboot, QtCore.SIGNAL("clicked()"), window.bootReboot)
        QtCore.QObject.connect(self.pushAppPath, QtCore.SIGNAL("clicked()"), window.bootChooseAppPath)
        QtCore.QObject.connect(self.pushR2pPath, QtCore.SIGNAL("clicked()"), window.settingsChooseR2pPath)
        QtCore.QObject.connect(self.pushChibiosPath, QtCore.SIGNAL("clicked()"), window.settingsChooseChibiosPath)
        QtCore.QObject.connect(self.pushModulePath, QtCore.SIGNAL("clicked()"), window.bootChooseModulePath)
        QtCore.QObject.connect(self.pushLogicalExpand, QtCore.SIGNAL("clicked()"), self.treeLogical.expandAll)
        QtCore.QObject.connect(self.pushLogicalCollapse, QtCore.SIGNAL("clicked()"), self.treeLogical.collapseAll)
        QtCore.QObject.connect(self.pushLogicalRefresh, QtCore.SIGNAL("clicked()"), window.logicalRefresh)
        QtCore.QObject.connect(self.pushPhysicalRefresh, QtCore.SIGNAL("clicked()"), window.physicalRefresh)
        QtCore.QObject.connect(self.pushModuleElf, QtCore.SIGNAL("clicked()"), window.bootChooseModuleElf)
        QtCore.QObject.connect(self.pushAppSrcElf, QtCore.SIGNAL("clicked()"), window.bootChooseAppSrcElf)
        QtCore.QObject.connect(self.pushAppDstElf, QtCore.SIGNAL("clicked()"), window.bootChooseAppDstElf)
        QtCore.QObject.connect(self.lineAppName, QtCore.SIGNAL("editingFinished()"), window.bootSetAppName)
        QtCore.QObject.connect(self.spinStackSize, QtCore.SIGNAL("editingFinished()"), window.bootSetStackSize)
        QtCore.QObject.connect(self.lineAppDstElf, QtCore.SIGNAL("editingFinished()"), window.bootSetAppDstElf)
        QtCore.QObject.connect(self.lineAppSrcElf, QtCore.SIGNAL("editingFinished()"), window.bootSetAppSrcElf)
        QtCore.QObject.connect(self.lineAppPath, QtCore.SIGNAL("editingFinished()"), window.bootSetAppPath)
        QtCore.QObject.connect(self.lineModuleElf, QtCore.SIGNAL("editingFinished()"), window.bootSetMouleElf)
        QtCore.QObject.connect(self.lineModulePath, QtCore.SIGNAL("editingFinished()"), window.bootSetModulePath)
        QtCore.QObject.connect(self.lineBootTopic, QtCore.SIGNAL("editingFinished()"), window.bootSetBootTopic)
        QtCore.QObject.connect(self.lineR2pPath, QtCore.SIGNAL("editingFinished()"), window.settingsSetR2pPath)
        QtCore.QObject.connect(self.lineChibiosPath, QtCore.SIGNAL("editingFinished()"), window.settingsSetChibiosPath)
        QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.tabWidget, self.lineBootTopic)
        window.setTabOrder(self.lineBootTopic, self.pushBootRefresh)
        window.setTabOrder(self.pushBootRefresh, self.tableApps)
        window.setTabOrder(self.tableApps, self.lineAppPath)
        window.setTabOrder(self.lineAppPath, self.pushAppPath)
        window.setTabOrder(self.pushAppPath, self.lineAppName)
        window.setTabOrder(self.lineAppName, self.spinStackSize)
        window.setTabOrder(self.spinStackSize, self.lineR2pPath)
        window.setTabOrder(self.lineR2pPath, self.pushR2pPath)
        window.setTabOrder(self.pushR2pPath, self.lineChibiosPath)
        window.setTabOrder(self.lineChibiosPath, self.pushChibiosPath)
        window.setTabOrder(self.pushChibiosPath, self.comboTransport)
        window.setTabOrder(self.comboTransport, self.pushPhysicalExpand)
        window.setTabOrder(self.pushPhysicalExpand, self.treePhysical)
        window.setTabOrder(self.treePhysical, self.pushPhysicalRefresh)
        window.setTabOrder(self.pushPhysicalRefresh, self.pushPhysicalCollapse)

    def retranslateUi(self, window):
        window.setWindowTitle(QtGui.QApplication.translate("window", "R2P bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLogicalCollapse.setText(QtGui.QApplication.translate("window", "&Collapse all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLogicalExpand.setText(QtGui.QApplication.translate("window", "&Expand all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLogicalRefresh.setText(QtGui.QApplication.translate("window", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogical), QtGui.QApplication.translate("window", "&Logical network", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabLogical), QtGui.QApplication.translate("window", "Bottom-up R2P network view", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalCollapse.setToolTip(QtGui.QApplication.translate("window", "Collapses the tree view", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalCollapse.setText(QtGui.QApplication.translate("window", "&Collapse all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalExpand.setToolTip(QtGui.QApplication.translate("window", "Expands the tree view", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalExpand.setText(QtGui.QApplication.translate("window", "&Expand all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalRefresh.setToolTip(QtGui.QApplication.translate("window", "Refreshes the network tree view", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPhysicalRefresh.setText(QtGui.QApplication.translate("window", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPhysical), QtGui.QApplication.translate("window", "&Physical network", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabPhysical), QtGui.QApplication.translate("window", "Top-down R2P network view", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBootTopic.setText(QtGui.QApplication.translate("window", "Boot topic", None, QtGui.QApplication.UnicodeUTF8))
        self.lineBootTopic.setToolTip(QtGui.QApplication.translate("window", "Bootloader topic name of the target module", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRefresh.setToolTip(QtGui.QApplication.translate("window", "Refreshes the list of installed apps on the chosen module", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRefresh.setText(QtGui.QApplication.translate("window", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tableApps.setToolTip(QtGui.QApplication.translate("window", "Installed apps", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("window", "Module path", None, QtGui.QApplication.UnicodeUTF8))
        self.lineModulePath.setToolTip(QtGui.QApplication.translate("window", "Path of the target module firmware root folder", None, QtGui.QApplication.UnicodeUTF8))
        self.lineModulePath.setPlaceholderText(QtGui.QApplication.translate("window", "/opt/r2p/modules/MyModule", None, QtGui.QApplication.UnicodeUTF8))
        self.pushModulePath.setText(QtGui.QApplication.translate("window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAppPath.setText(QtGui.QApplication.translate("window", "App path", None, QtGui.QApplication.UnicodeUTF8))
        self.lineAppPath.setToolTip(QtGui.QApplication.translate("window", "Path of the app root folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushAppPath.setText(QtGui.QApplication.translate("window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAppName.setText(QtGui.QApplication.translate("window", "App name", None, QtGui.QApplication.UnicodeUTF8))
        self.lineAppName.setToolTip(QtGui.QApplication.translate("window", "App identifier", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStackSize.setText(QtGui.QApplication.translate("window", "Stack size", None, QtGui.QApplication.UnicodeUTF8))
        self.spinStackSize.setToolTip(QtGui.QApplication.translate("window", "Size of the stack allocated for the app main thread, *INCLUDING* the Thread Control Block", None, QtGui.QApplication.UnicodeUTF8))
        self.spinStackSize.setSuffix(QtGui.QApplication.translate("window", " B", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBootloader.setFormat(QtGui.QApplication.translate("window", "No app being installed", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootReboot.setToolTip(QtGui.QApplication.translate("window", "Reboots the target module", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootReboot.setText(QtGui.QApplication.translate("window", "Reb&oot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRemoveAll.setToolTip(QtGui.QApplication.translate("window", "Uninstalls all the apps from the target module", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRemoveAll.setText(QtGui.QApplication.translate("window", "Remove &all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRemoveLast.setToolTip(QtGui.QApplication.translate("window", "Uninstalls the last app from the target module", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBootRemoveLast.setText(QtGui.QApplication.translate("window", "Remo&ve last", None, QtGui.QApplication.UnicodeUTF8))
        self.pushInstall.setToolTip(QtGui.QApplication.translate("window", "Installs the app configured in the form above", None, QtGui.QApplication.UnicodeUTF8))
        self.pushInstall.setText(QtGui.QApplication.translate("window", "&Install", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("window", "Module ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("window", "App src ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.lineModuleElf.setToolTip(QtGui.QApplication.translate("window", "Path of the target module firmware ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushModuleElf.setText(QtGui.QApplication.translate("window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineAppSrcElf.setToolTip(QtGui.QApplication.translate("window", "Path of the app source (unlinked) ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.lineAppSrcElf.setPlaceholderText(QtGui.QApplication.translate("window", "/opt/r2p/apps/MyApp/build/MyApp.elf", None, QtGui.QApplication.UnicodeUTF8))
        self.pushAppSrcElf.setText(QtGui.QApplication.translate("window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("window", "App dst ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.lineAppDstElf.setToolTip(QtGui.QApplication.translate("window", "Path of the app destination (linked) ELF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushAppDstElf.setText(QtGui.QApplication.translate("window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBootloader), QtGui.QApplication.translate("window", "&Bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabBootloader), QtGui.QApplication.translate("window", "App bootloader", None, QtGui.QApplication.UnicodeUTF8))
        self.labelR2pPath.setText(QtGui.QApplication.translate("window", "R2P path", None, QtGui.QApplication.UnicodeUTF8))
        self.lineR2pPath.setToolTip(QtGui.QApplication.translate("window", "Path of the R2P root folder", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChibiosPath.setText(QtGui.QApplication.translate("window", "ChibiOS/RT path", None, QtGui.QApplication.UnicodeUTF8))
        self.lineChibiosPath.setToolTip(QtGui.QApplication.translate("window", "Path of the ChibiOS/RT root folder", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTransport.setText(QtGui.QApplication.translate("window", "Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTransport.setToolTip(QtGui.QApplication.translate("window", "<html><head/><body><p>Gateway transport</p><p><br/></p><p>{TODO; current: DebugTransport(&quot;/dev/ttyUSB0&quot;, 115200)}</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("window", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("window", "Global settings", None, QtGui.QApplication.UnicodeUTF8))

